---
apiVersion: v1
kind: ConfigMap
metadata:
  name: key-map
  namespace: gatekeeper
data:
  horismos_config: |-
    base_key_path: "/tmp/keys"
    key_map:
      image: "cosign.pub"
      'sbom.sources': "cosign.sbom.pub"
    port: 8085
  image: |-
{{ indent 4 .Values.verifyimage.key }}
  'sbom.sources': |-
{{ indent 4 .Values.verifyimage.key }}
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-signing-checker-service
  namespace: gatekeeper
spec:
  selector:
    app: gatekeeper-signing-checker
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
