apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kaniko-cargo-pipeline-run-{{ .Release.Revision }}
  labels:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: kaniko-cargo-pipeline
  params:
  - name: image
    # NOTE: Change me to something like  below if you want to test out without access to push mlieberman85/kaniko-chains-demo
    # value: ttl.sh/foo-kaniko-chains-demo:1h
    value: {{ .Values.pipelinerun.image }}
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: kaniko-source-pvc
  - name: docker-secrets
    secret:
      secretName: secret-dockerconfigjson
  - name: sboms
    emptyDir: {}
  - name: sbom-key
    secret:
      secretName: sbom
